
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 1
blur = false

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14.0

[general]
import = [
  "~/.config/alacritty/themes/themes/_active.toml"
]
